<?php

namespace Modules\Accounting\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Accounting\Models\Account;

class CatalogoCuentasMexicanoSeeder extends Seeder
{
    /**
     * Seed Mexican Chart of Accounts (Catálogo de Cuentas Mexicano)
     * Based on standard accounting practices for Mexican businesses
     */
    public function run(): void
    {
        $accounts = $this->getChartOfAccounts();

        foreach ($accounts as $accountData) {
            Account::firstOrCreate(
                ['code' => $accountData['code'], 'company_id' => 1],
                $accountData
            );
        }

        $this->command->info('Mexican Chart of Accounts seeded successfully');
    }

    /**
     * Get complete Mexican chart of accounts structure
     */
    private function getChartOfAccounts(): array
    {
        return [
            // ========================================
            // 1000 - ACTIVO
            // ========================================
            [
                'code' => '1000',
                'name' => 'ACTIVO',
                'account_type' => 'asset',
                'level' => 1,
                'is_postable' => false,
                'parent_id' => null,
                'company_id' => 1,
                'status' => 'active',
            ],

            // 1100 - ACTIVO CIRCULANTE
            [
                'code' => '1100',
                'name' => 'ACTIVO CIRCULANTE',
                'account_type' => 'asset',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '1000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1101',
                'name' => 'Caja',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1102',
                'name' => 'Bancos',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1103',
                'name' => 'Inversiones Temporales',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1104',
                'name' => 'Clientes',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1105',
                'name' => 'Documentos por Cobrar',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1106',
                'name' => 'Deudores Diversos',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1107',
                'name' => 'IVA Acreditable',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1108',
                'name' => 'Almacén',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1109',
                'name' => 'Anticipos a Proveedores',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1100',
                'company_id' => 1,
                'status' => 'active',
            ],

            // 1200 - ACTIVO NO CIRCULANTE (FIJO)
            [
                'code' => '1200',
                'name' => 'ACTIVO NO CIRCULANTE',
                'account_type' => 'asset',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '1000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1201',
                'name' => 'Terrenos',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1202',
                'name' => 'Edificios',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1203',
                'name' => 'Maquinaria y Equipo',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1204',
                'name' => 'Equipo de Transporte',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1205',
                'name' => 'Mobiliario y Equipo de Oficina',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1206',
                'name' => 'Equipo de Cómputo',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1207',
                'name' => 'Depreciación Acumulada',
                'account_type' => 'contra',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1200',
                'company_id' => 1,
                'status' => 'active',
            ],

            // 1300 - ACTIVO DIFERIDO
            [
                'code' => '1300',
                'name' => 'ACTIVO DIFERIDO',
                'account_type' => 'asset',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '1000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1301',
                'name' => 'Gastos de Instalación',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1300',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1302',
                'name' => 'Gastos de Organización',
                'account_type' => 'asset',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1300',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '1303',
                'name' => 'Amortización Acumulada',
                'account_type' => 'contra',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '1300',
                'company_id' => 1,
                'status' => 'active',
            ],

            // ========================================
            // 2000 - PASIVO
            // ========================================
            [
                'code' => '2000',
                'name' => 'PASIVO',
                'account_type' => 'liability',
                'level' => 1,
                'is_postable' => false,
                'parent_id' => null,
                'company_id' => 1,
                'status' => 'active',
            ],

            // 2100 - PASIVO CIRCULANTE (CORTO PLAZO)
            [
                'code' => '2100',
                'name' => 'PASIVO CIRCULANTE',
                'account_type' => 'liability',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '2000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2101',
                'name' => 'Proveedores',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2102',
                'name' => 'Documentos por Pagar',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2103',
                'name' => 'Acreedores Diversos',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2104',
                'name' => 'IVA por Pagar',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2105',
                'name' => 'ISR por Pagar',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2106',
                'name' => 'IMSS por Pagar',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2107',
                'name' => 'Préstamos Bancarios Corto Plazo',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2108',
                'name' => 'Anticipo de Clientes',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2100',
                'company_id' => 1,
                'status' => 'active',
            ],

            // 2200 - PASIVO NO CIRCULANTE (LARGO PLAZO)
            [
                'code' => '2200',
                'name' => 'PASIVO NO CIRCULANTE',
                'account_type' => 'liability',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '2000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2201',
                'name' => 'Préstamos Bancarios Largo Plazo',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '2202',
                'name' => 'Hipotecas por Pagar',
                'account_type' => 'liability',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '2200',
                'company_id' => 1,
                'status' => 'active',
            ],

            // ========================================
            // 3000 - CAPITAL CONTABLE
            // ========================================
            [
                'code' => '3000',
                'name' => 'CAPITAL CONTABLE',
                'account_type' => 'equity',
                'level' => 1,
                'is_postable' => false,
                'parent_id' => null,
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '3100',
                'name' => 'CAPITAL CONTRIBUIDO',
                'account_type' => 'equity',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '3000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '3101',
                'name' => 'Capital Social',
                'account_type' => 'equity',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '3100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '3102',
                'name' => 'Aportaciones para Futuros Aumentos de Capital',
                'account_type' => 'equity',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '3100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '3200',
                'name' => 'CAPITAL GANADO',
                'account_type' => 'equity',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '3000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '3201',
                'name' => 'Utilidades Retenidas',
                'account_type' => 'equity',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '3200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '3202',
                'name' => 'Utilidad del Ejercicio',
                'account_type' => 'equity',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '3200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '3203',
                'name' => 'Pérdida del Ejercicio',
                'account_type' => 'equity',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '3200',
                'company_id' => 1,
                'status' => 'active',
            ],

            // ========================================
            // 4000 - INGRESOS
            // ========================================
            [
                'code' => '4000',
                'name' => 'INGRESOS',
                'account_type' => 'revenue',
                'level' => 1,
                'is_postable' => false,
                'parent_id' => null,
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '4100',
                'name' => 'INGRESOS POR VENTAS',
                'account_type' => 'revenue',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '4000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '4101',
                'name' => 'Ventas',
                'account_type' => 'revenue',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '4100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '4102',
                'name' => 'Devoluciones sobre Ventas',
                'account_type' => 'contra',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '4100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '4103',
                'name' => 'Descuentos sobre Ventas',
                'account_type' => 'contra',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '4100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '4200',
                'name' => 'OTROS INGRESOS',
                'account_type' => 'revenue',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '4000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '4201',
                'name' => 'Productos Financieros',
                'account_type' => 'revenue',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '4200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '4202',
                'name' => 'Otros Ingresos',
                'account_type' => 'revenue',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '4200',
                'company_id' => 1,
                'status' => 'active',
            ],

            // ========================================
            // 5000 - COSTOS
            // ========================================
            [
                'code' => '5000',
                'name' => 'COSTOS',
                'account_type' => 'expense',
                'level' => 1,
                'is_postable' => false,
                'parent_id' => null,
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '5100',
                'name' => 'COSTO DE VENTAS',
                'account_type' => 'expense',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '5000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '5101',
                'name' => 'Costo de Ventas',
                'account_type' => 'expense',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '5100',
                'company_id' => 1,
                'status' => 'active',
            ],

            // ========================================
            // 6000 - GASTOS
            // ========================================
            [
                'code' => '6000',
                'name' => 'GASTOS',
                'account_type' => 'expense',
                'level' => 1,
                'is_postable' => false,
                'parent_id' => null,
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6100',
                'name' => 'GASTOS DE OPERACIÓN',
                'account_type' => 'expense',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '6000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6110',
                'name' => 'Gastos de Venta',
                'account_type' => 'expense',
                'level' => 3,
                'is_postable' => false,
                'parent_code' => '6100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6111',
                'name' => 'Sueldos y Salarios - Ventas',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6110',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6112',
                'name' => 'Comisiones sobre Ventas',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6110',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6113',
                'name' => 'Publicidad',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6110',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6120',
                'name' => 'Gastos de Administración',
                'account_type' => 'expense',
                'level' => 3,
                'is_postable' => false,
                'parent_code' => '6100',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6121',
                'name' => 'Sueldos y Salarios - Administración',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6120',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6122',
                'name' => 'Honorarios',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6120',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6123',
                'name' => 'Renta',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6120',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6124',
                'name' => 'Luz',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6120',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6125',
                'name' => 'Teléfono e Internet',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6120',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6126',
                'name' => 'Papelería y Útiles',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6120',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6127',
                'name' => 'Depreciaciones',
                'account_type' => 'expense',
                'level' => 4,
                'is_postable' => true,
                'parent_code' => '6120',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6200',
                'name' => 'GASTOS FINANCIEROS',
                'account_type' => 'expense',
                'level' => 2,
                'is_postable' => false,
                'parent_code' => '6000',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6201',
                'name' => 'Intereses sobre Préstamos',
                'account_type' => 'expense',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '6200',
                'company_id' => 1,
                'status' => 'active',
            ],
            [
                'code' => '6202',
                'name' => 'Comisiones Bancarias',
                'account_type' => 'expense',
                'level' => 3,
                'is_postable' => true,
                'parent_code' => '6200',
                'company_id' => 1,
                'status' => 'active',
            ],
        ];
    }
}
