<?php

namespace Modules\MailerManager\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\MailerManager\Models\SystemEmail;

class SystemEmailSeeder extends Seeder
{
    public function run(): void
    {
        $emails = $this->getSystemEmails();

        foreach ($emails as $data) {
            SystemEmail::updateOrCreate(
                ['key' => $data['key']],
                $data
            );
        }
    }

    protected function getSystemEmails(): array
    {
        return [
            // === ECOMMERCE MODULE ===
            [
                'key' => 'ecommerce.order_confirmation.customer',
                'module' => 'Ecommerce',
                'name' => 'Confirmacion de Orden (Cliente)',
                'description' => 'Se envia al cliente cuando se crea una nueva orden de compra.',
                'mailable_class' => 'Modules\\Ecommerce\\Mail\\OrderConfirmationMail',
                'available_variables' => [
                    'order_number' => 'Numero de orden',
                    'customer_name' => 'Nombre del cliente',
                    'customer_email' => 'Email del cliente',
                    'order_date' => 'Fecha de la orden',
                    'subtotal' => 'Subtotal',
                    'tax' => 'IVA',
                    'total' => 'Total',
                    'currency' => 'Moneda',
                    'status' => 'Estado de la orden',
                    'items' => 'Productos [{name, sku, quantity, unit_price, subtotal}]',
                    'shipping_address' => 'Direccion de envio',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Juan Perez',
                    'customer_email' => 'juan@example.com',
                    'order_date' => '16/03/2026',
                    'subtotal' => 2599.98,
                    'tax' => 416.00,
                    'total' => 3015.98,
                    'currency' => 'MXN',
                    'status' => 'confirmed',
                    'items' => [
                        ['name' => 'iPhone 15 Pro', 'sku' => 'APL-IPH15P-256', 'quantity' => 2, 'unit_price' => 1299.99, 'subtotal' => 2599.98],
                    ],
                    'shipping_address' => 'Av. Reforma 123, CDMX, 06600',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Confirmacion de tu orden {{order_number}}',
            ],
            [
                'key' => 'ecommerce.order_confirmation.admin',
                'module' => 'Ecommerce',
                'name' => 'Nueva Orden Recibida (Admin)',
                'description' => 'Notificacion al administrador cuando se recibe una nueva orden.',
                'mailable_class' => 'Modules\\Ecommerce\\Mail\\OrderConfirmationMail',
                'available_variables' => [
                    'order_number' => 'Numero de orden',
                    'customer_name' => 'Nombre del cliente',
                    'customer_email' => 'Email del cliente',
                    'order_date' => 'Fecha de la orden',
                    'subtotal' => 'Subtotal',
                    'tax' => 'IVA',
                    'total' => 'Total',
                    'currency' => 'Moneda',
                    'items' => 'Productos [{name, sku, quantity, unit_price, subtotal}]',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Juan Perez',
                    'customer_email' => 'juan@example.com',
                    'order_date' => '16/03/2026',
                    'subtotal' => 2599.98,
                    'tax' => 416.00,
                    'total' => 3015.98,
                    'currency' => 'MXN',
                    'items' => [
                        ['name' => 'iPhone 15 Pro', 'sku' => 'APL-IPH15P-256', 'quantity' => 2, 'unit_price' => 1299.99, 'subtotal' => 2599.98],
                    ],
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Nueva orden recibida: {{order_number}}',
            ],
            [
                'key' => 'ecommerce.payment_confirmation',
                'module' => 'Ecommerce',
                'name' => 'Confirmacion de Pago',
                'description' => 'Se envia al cliente cuando su pago ha sido procesado exitosamente.',
                'mailable_class' => 'Modules\\Ecommerce\\Mail\\PaymentConfirmationMail',
                'available_variables' => [
                    'order_number' => 'Numero de orden',
                    'customer_name' => 'Nombre del cliente',
                    'payment_amount' => 'Monto del pago',
                    'payment_method' => 'Metodo de pago',
                    'payment_date' => 'Fecha del pago',
                    'transaction_id' => 'ID de transaccion',
                    'currency' => 'Moneda',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Juan Perez',
                    'payment_amount' => 3015.98,
                    'payment_method' => 'Tarjeta de credito',
                    'payment_date' => '16/03/2026',
                    'transaction_id' => 'pi_3abc123def456',
                    'currency' => 'MXN',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Pago confirmado - Orden {{order_number}}',
            ],
            [
                'key' => 'ecommerce.shipping_notification',
                'module' => 'Ecommerce',
                'name' => 'Notificacion de Envio',
                'description' => 'Se envia al cliente cuando su pedido ha sido enviado.',
                'mailable_class' => 'Modules\\Ecommerce\\Mail\\ShippingNotificationMail',
                'available_variables' => [
                    'order_number' => 'Numero de orden',
                    'customer_name' => 'Nombre del cliente',
                    'tracking_number' => 'Numero de rastreo',
                    'carrier' => 'Paqueteria',
                    'estimated_delivery' => 'Fecha estimada de entrega',
                    'shipping_address' => 'Direccion de envio',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Juan Perez',
                    'tracking_number' => 'MX1234567890',
                    'carrier' => 'DHL Express',
                    'estimated_delivery' => '20/03/2026',
                    'shipping_address' => 'Av. Reforma 123, CDMX, 06600',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Tu pedido {{order_number}} ha sido enviado',
            ],
            [
                'key' => 'ecommerce.order_status_update',
                'module' => 'Ecommerce',
                'name' => 'Cambio de Estado de Orden',
                'description' => 'Se envia al cliente cuando el estado de su orden cambia.',
                'mailable_class' => 'Modules\\Ecommerce\\Mail\\OrderStatusUpdateMail',
                'available_variables' => [
                    'order_number' => 'Numero de orden',
                    'customer_name' => 'Nombre del cliente',
                    'previous_status' => 'Estado anterior',
                    'new_status' => 'Nuevo estado',
                    'notes' => 'Notas adicionales',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Juan Perez',
                    'previous_status' => 'processing',
                    'new_status' => 'shipped',
                    'notes' => 'Su pedido ha sido entregado a la paqueteria.',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Actualizacion de tu orden {{order_number}}',
            ],
            [
                'key' => 'ecommerce.order_cancellation',
                'module' => 'Ecommerce',
                'name' => 'Cancelacion de Orden',
                'description' => 'Se envia al cliente cuando su orden es cancelada.',
                'mailable_class' => 'Modules\\Ecommerce\\Mail\\OrderCancellationMail',
                'available_variables' => [
                    'order_number' => 'Numero de orden',
                    'customer_name' => 'Nombre del cliente',
                    'cancellation_reason' => 'Razon de cancelacion',
                    'total' => 'Total de la orden',
                    'currency' => 'Moneda',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Juan Perez',
                    'cancellation_reason' => 'Solicitud del cliente',
                    'total' => 3015.98,
                    'currency' => 'MXN',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Orden {{order_number}} cancelada',
            ],
            [
                'key' => 'ecommerce.order_return.customer',
                'module' => 'Ecommerce',
                'name' => 'Solicitud de Devolucion (Cliente)',
                'description' => 'Confirmacion al cliente de que su solicitud de devolucion ha sido recibida.',
                'mailable_class' => 'Modules\\Ecommerce\\Mail\\OrderReturnRequestMail',
                'available_variables' => [
                    'order_number' => 'Numero de orden',
                    'customer_name' => 'Nombre del cliente',
                    'return_reason' => 'Razon de devolucion',
                    'items' => 'Productos a devolver [{name, quantity}]',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Juan Perez',
                    'return_reason' => 'Producto defectuoso',
                    'items' => [
                        ['name' => 'iPhone 15 Pro', 'quantity' => 1],
                    ],
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Solicitud de devolucion recibida - Orden {{order_number}}',
            ],
            [
                'key' => 'ecommerce.order_return.admin',
                'module' => 'Ecommerce',
                'name' => 'Solicitud de Devolucion (Admin)',
                'description' => 'Notificacion al administrador de nueva solicitud de devolucion.',
                'mailable_class' => 'Modules\\Ecommerce\\Mail\\OrderReturnRequestMail',
                'available_variables' => [
                    'order_number' => 'Numero de orden',
                    'customer_name' => 'Nombre del cliente',
                    'customer_email' => 'Email del cliente',
                    'return_reason' => 'Razon de devolucion',
                    'items' => 'Productos a devolver [{name, quantity}]',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Juan Perez',
                    'customer_email' => 'juan@example.com',
                    'return_reason' => 'Producto defectuoso',
                    'items' => [
                        ['name' => 'iPhone 15 Pro', 'quantity' => 1],
                    ],
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Nueva solicitud de devolucion - Orden {{order_number}}',
            ],
            [
                'key' => 'ecommerce.refund_confirmation',
                'module' => 'Ecommerce',
                'name' => 'Confirmacion de Reembolso',
                'description' => 'Se envia al cliente cuando se procesa un reembolso.',
                'mailable_class' => 'Modules\\Ecommerce\\Mail\\OrderStatusUpdateMail',
                'available_variables' => [
                    'order_number' => 'Numero de orden',
                    'customer_name' => 'Nombre del cliente',
                    'refund_amount' => 'Monto del reembolso',
                    'currency' => 'Moneda',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Juan Perez',
                    'refund_amount' => 1299.99,
                    'currency' => 'MXN',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Reembolso procesado - Orden {{order_number}}',
            ],

            // === SALES MODULE ===
            [
                'key' => 'sales.quote_requested.admin',
                'module' => 'Sales',
                'name' => 'Nueva Solicitud de Cotizacion (Admin)',
                'description' => 'Notificacion al administrador cuando un cliente solicita una cotizacion.',
                'mailable_class' => 'Modules\\Sales\\Mail\\QuoteRequestedMail',
                'available_variables' => [
                    'quote_number' => 'Numero de cotizacion',
                    'customer_name' => 'Nombre del cliente',
                    'customer_email' => 'Email del cliente',
                    'quote_date' => 'Fecha de cotizacion',
                    'items' => 'Productos [{name, sku, quantity, price, subtotal}]',
                    'total' => 'Total',
                    'currency' => 'Moneda',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'quote_number' => 'COT-26000001',
                    'customer_name' => 'Braun, Reichert and Padberg',
                    'customer_email' => 'gstanton@example.com',
                    'quote_date' => '16/03/2026',
                    'items' => [
                        ['name' => 'iPhone 15 Pro', 'sku' => 'APL-IPH15P-256', 'quantity' => 2, 'price' => 1299.99, 'subtotal' => 2599.98],
                    ],
                    'total' => 3015.98,
                    'currency' => 'MXN',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Nueva solicitud de cotizacion {{quote_number}}',
            ],
            [
                'key' => 'sales.quote_requested.customer',
                'module' => 'Sales',
                'name' => 'Solicitud de Cotizacion Recibida (Cliente)',
                'description' => 'Confirmacion al cliente de que su solicitud de cotizacion fue recibida.',
                'mailable_class' => 'Modules\\Sales\\Mail\\QuoteRequestedMail',
                'available_variables' => [
                    'quote_number' => 'Numero de cotizacion',
                    'customer_name' => 'Nombre del cliente',
                    'quote_date' => 'Fecha de cotizacion',
                    'items' => 'Productos [{name, sku, quantity}]',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'quote_number' => 'COT-26000001',
                    'customer_name' => 'Braun, Reichert and Padberg',
                    'quote_date' => '16/03/2026',
                    'items' => [
                        ['name' => 'iPhone 15 Pro', 'sku' => 'APL-IPH15P-256', 'quantity' => 2],
                    ],
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Su solicitud de cotizacion {{quote_number}} ha sido recibida',
            ],
            [
                'key' => 'sales.quote_sent',
                'module' => 'Sales',
                'name' => 'Cotizacion Enviada al Cliente',
                'description' => 'Se envia al cliente con la cotizacion formal y PDF adjunto.',
                'mailable_class' => 'Modules\\Sales\\Mail\\QuoteSentMail',
                'available_variables' => [
                    'quote_number' => 'Numero de cotizacion',
                    'customer_name' => 'Nombre del cliente',
                    'customer_email' => 'Email del cliente',
                    'quote_date' => 'Fecha de cotizacion',
                    'valid_until' => 'Fecha de vigencia',
                    'subtotal' => 'Subtotal',
                    'tax' => 'IVA',
                    'total' => 'Total',
                    'currency' => 'Moneda',
                    'items' => 'Productos [{name, sku, quantity, price, subtotal}]',
                    'notes' => 'Notas de la cotizacion',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'quote_number' => 'COT-26000001',
                    'customer_name' => 'Braun, Reichert and Padberg',
                    'customer_email' => 'gstanton@example.com',
                    'quote_date' => '16/03/2026',
                    'valid_until' => '15/04/2026',
                    'subtotal' => 2599.98,
                    'tax' => 416.00,
                    'total' => 3015.98,
                    'currency' => 'MXN',
                    'items' => [
                        ['name' => 'iPhone 15 Pro', 'sku' => 'APL-IPH15P-256', 'quantity' => 2, 'price' => 1299.99, 'subtotal' => 2599.98],
                    ],
                    'notes' => 'Precios validos por 30 dias.',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Cotizacion {{quote_number}}',
            ],
            [
                'key' => 'sales.quote_converted.customer',
                'module' => 'Sales',
                'name' => 'Cotizacion Convertida a Orden (Cliente)',
                'description' => 'Se envia al cliente cuando su cotizacion ha sido convertida en orden de venta.',
                'mailable_class' => 'Modules\\Sales\\Mail\\QuoteConvertedMail',
                'available_variables' => [
                    'quote_number' => 'Numero de cotizacion',
                    'order_number' => 'Numero de orden generada',
                    'customer_name' => 'Nombre del cliente',
                    'total' => 'Total',
                    'currency' => 'Moneda',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'quote_number' => 'COT-26000001',
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Braun, Reichert and Padberg',
                    'total' => 3015.98,
                    'currency' => 'MXN',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Su cotizacion {{quote_number}} ha sido convertida en orden',
            ],
            [
                'key' => 'sales.quote_converted.admin',
                'module' => 'Sales',
                'name' => 'Cotizacion Convertida a Orden (Admin)',
                'description' => 'Notificacion al administrador cuando una cotizacion se convierte en orden.',
                'mailable_class' => 'Modules\\Sales\\Mail\\QuoteConvertedMail',
                'available_variables' => [
                    'quote_number' => 'Numero de cotizacion',
                    'order_number' => 'Numero de orden generada',
                    'customer_name' => 'Nombre del cliente',
                    'customer_email' => 'Email del cliente',
                    'total' => 'Total',
                    'currency' => 'Moneda',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'quote_number' => 'COT-26000001',
                    'order_number' => 'OV-26000001',
                    'customer_name' => 'Braun, Reichert and Padberg',
                    'customer_email' => 'gstanton@example.com',
                    'total' => 3015.98,
                    'currency' => 'MXN',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Cotizacion {{quote_number}} convertida a orden {{order_number}}',
            ],

            // === BILLING MODULE ===
            [
                'key' => 'billing.cfdi_invoice_sent',
                'module' => 'Billing',
                'name' => 'Factura CFDI Enviada',
                'description' => 'Se envia al cliente con la factura CFDI (PDF y XML adjuntos).',
                'mailable_class' => 'closure',
                'available_variables' => [
                    'invoice_folio' => 'Folio de la factura',
                    'invoice_uuid' => 'UUID fiscal',
                    'customer_name' => 'Nombre del cliente (razon social)',
                    'customer_rfc' => 'RFC del cliente',
                    'subtotal' => 'Subtotal',
                    'tax' => 'IVA',
                    'total' => 'Total',
                    'currency' => 'Moneda',
                    'invoice_date' => 'Fecha de emision',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'invoice_folio' => 'FAC-001',
                    'invoice_uuid' => 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                    'customer_name' => 'Braun, Reichert and Padberg SA de CV',
                    'customer_rfc' => 'BRP200101ABC',
                    'subtotal' => 2599.98,
                    'tax' => 416.00,
                    'total' => 3015.98,
                    'currency' => 'MXN',
                    'invoice_date' => '16/03/2026',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Factura {{invoice_folio}} - {{company_name}}',
            ],

            // === INVENTORY MODULE ===
            [
                'key' => 'inventory.gl_posting_failed',
                'module' => 'Inventory',
                'name' => 'Error de Contabilizacion GL',
                'description' => 'Notificacion al equipo de contabilidad cuando falla el posteo GL de un movimiento de inventario.',
                'mailable_class' => 'Modules\\Inventory\\Mail\\GLPostingFailedMail',
                'available_variables' => [
                    'movement_id' => 'ID del movimiento',
                    'movement_type' => 'Tipo de movimiento',
                    'product_name' => 'Producto',
                    'warehouse_name' => 'Almacen',
                    'error_message' => 'Mensaje de error',
                    'retry_attempts' => 'Intentos de reintento',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'movement_id' => 42,
                    'movement_type' => 'receipt',
                    'product_name' => 'iPhone 15 Pro',
                    'warehouse_name' => 'Almacen Principal',
                    'error_message' => 'Account mapping not found for product category',
                    'retry_attempts' => 3,
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Error de contabilizacion - Movimiento #{{movement_id}}',
            ],

            // === AUTH MODULE ===
            [
                'key' => 'auth.welcome',
                'module' => 'Auth',
                'name' => 'Bienvenida al Sistema',
                'description' => 'Se envia al usuario cuando se registra en el sistema.',
                'mailable_class' => 'Modules\\Auth\\Notifications\\WelcomeNotification',
                'available_variables' => [
                    'user_name' => 'Nombre del usuario',
                    'user_email' => 'Email del usuario',
                    'login_url' => 'URL de login',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'user_name' => 'Juan Perez',
                    'user_email' => 'juan@example.com',
                    'login_url' => 'http://localhost:3000/auth/login',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Bienvenido a {{company_name}}',
            ],
            [
                'key' => 'auth.verify_email',
                'module' => 'Auth',
                'name' => 'Verificacion de Email',
                'description' => 'Se envia para verificar la direccion de correo del usuario.',
                'mailable_class' => 'Modules\\Auth\\Notifications\\VerifyEmailNotification',
                'available_variables' => [
                    'user_name' => 'Nombre del usuario',
                    'verification_url' => 'URL de verificacion',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'user_name' => 'Juan Perez',
                    'verification_url' => 'http://localhost:8000/api/auth/verify/1/abc123',
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Verifica tu correo electronico',
            ],
            [
                'key' => 'auth.reset_password',
                'module' => 'Auth',
                'name' => 'Recuperacion de Contrasena',
                'description' => 'Se envia cuando el usuario solicita restablecer su contrasena.',
                'mailable_class' => 'Modules\\Auth\\Notifications\\ResetPasswordNotification',
                'available_variables' => [
                    'user_name' => 'Nombre del usuario',
                    'reset_url' => 'URL para restablecer contrasena',
                    'expiration_minutes' => 'Minutos de vigencia del enlace',
                    'company_name' => 'Nombre de la empresa',
                ],
                'sample_data' => [
                    'user_name' => 'Juan Perez',
                    'reset_url' => 'http://localhost:3000/auth/reset-password?token=abc123',
                    'expiration_minutes' => 60,
                    'company_name' => 'Demo Company',
                ],
                'is_enabled' => true,
                'default_subject' => 'Restablecer contrasena',
            ],
        ];
    }
}
